# Generated by Django 3.2.4 on 2021-07-04 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indoor_temp', models.DecimalField(decimal_places=3, max_digits=3)),
                ('outdoor_temp', models.DecimalField(decimal_places=3, max_digits=3)),
                ('dew_point', models.DecimalField(decimal_places=3, max_digits=3)),
                ('wind_chill', models.DecimalField(decimal_places=3, max_digits=3)),
                ('indoor_humidity', models.DecimalField(decimal_places=3, max_digits=3)),
                ('outdoor_humidity', models.DecimalField(decimal_places=3, max_digits=3)),
                ('wind_speed', models.DecimalField(decimal_places=3, max_digits=3)),
                ('wind_gust', models.DecimalField(decimal_places=3, max_digits=3)),
                ('wind_direction', models.DecimalField(decimal_places=3, max_digits=3)),
                ('absolute_pressure', models.DecimalField(decimal_places=3, max_digits=3)),
                ('pressure', models.DecimalField(decimal_places=3, max_digits=3)),
                ('rain', models.DecimalField(decimal_places=3, max_digits=3)),
                ('daily_rain', models.DecimalField(decimal_places=3, max_digits=3)),
                ('weekly_rain', models.DecimalField(decimal_places=3, max_digits=3)),
                ('monthly_rain', models.DecimalField(decimal_places=3, max_digits=3)),
                ('solar_radiation', models.DecimalField(decimal_places=3, max_digits=3)),
                ('uv_index', models.IntegerField()),
                ('date_utc', models.DateTimeField()),
                ('software_type', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=100)),
                ('real_time', models.IntegerField()),
                ('radio_freq', models.IntegerField()),
            ],
        ),
    ]
