# Generated by Django 3.2.4 on 2021-07-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherdata',
            name='absolute_pressure',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='daily_rain',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='dew_point',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='indoor_humidity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='indoor_temp',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='monthly_rain',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='outdoor_humidity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='outdoor_temp',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='pressure',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='rain',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='solar_radiation',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='weekly_rain',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='wind_chill',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='wind_direction',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='wind_gust',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='wind_speed',
            field=models.FloatField(),
        ),
    ]
