# Generated by Django 3.2.4 on 2021-07-10 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20210709_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherdata',
            name='time_stamp',
            field=models.IntegerField(db_index=True, default=0),
            preserve_default=False,
        ),
    ]
