# Generated by Django 3.2.4 on 2022-09-16 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_partitions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weatherdata',
            options={},
        ),
        migrations.AddIndex(
            model_name='weatherdata',
            index=models.Index(fields=['indoor_temp', 'time_year'], name='weather_wea_indoor__d5513a_idx'),
        ),
        migrations.AddIndex(
            model_name='weatherdata',
            index=models.Index(fields=['outdoor_temp', 'time_year'], name='weather_wea_outdoor_6b76aa_idx'),
        ),
        migrations.AddIndex(
            model_name='weatherdata',
            index=models.Index(fields=['indoor_feels_temp', 'time_year'], name='weather_wea_indoor__858815_idx'),
        ),
        migrations.AddIndex(
            model_name='weatherdata',
            index=models.Index(fields=['outdoor_feels_temp', 'time_year'], name='weather_wea_outdoor_b1f3e6_idx'),
        ),
        migrations.AddIndex(
            model_name='weatherdata',
            index=models.Index(fields=['indoor_dew_temp', 'time_year'], name='weather_wea_indoor__b9bbf1_idx'),
        ),
        migrations.AddIndex(
            model_name='weatherdata',
            index=models.Index(fields=['outdoor_dew_temp', 'time_year'], name='weather_wea_outdoor_f40154_idx'),
        ),
        migrations.AddIndex(
            model_name='weatherdata',
            index=models.Index(fields=['dew_point', 'time_year'], name='weather_wea_dew_poi_1a2d4e_idx'),
        ),
        migrations.AddIndex(
            model_name='weatherdata',
            index=models.Index(fields=['wind_chill', 'time_year'], name='weather_wea_wind_ch_5a23dc_idx'),
        ),
        migrations.AddIndex(
            model_name='weatherdata',
            index=models.Index(fields=['indoor_humidity', 'time_year'], name='weather_wea_indoor__2e0fb6_idx'),
        ),
        migrations.AddIndex(
            model_name='weatherdata',
            index=models.Index(fields=['outdoor_humidity', 'time_year'], name='weather_wea_outdoor_c57950_idx'),
        ),
        migrations.AddIndex(
            model_name='weatherdata',
            index=models.Index(fields=['wind_speed', 'time_year'], name='weather_wea_wind_sp_7a40b5_idx'),
        ),
        migrations.AddIndex(
            model_name='weatherdata',
            index=models.Index(fields=['wind_gust', 'time_year'], name='weather_wea_wind_gu_1e980e_idx'),
        ),
        migrations.AddIndex(
            model_name='weatherdata',
            index=models.Index(fields=['wind_direction', 'time_year'], name='weather_wea_wind_di_0fedf3_idx'),
        ),
        migrations.AddIndex(
            model_name='weatherdata',
            index=models.Index(fields=['absolute_pressure', 'time_year'], name='weather_wea_absolut_ac86c1_idx'),
        ),
        migrations.AddIndex(
            model_name='weatherdata',
            index=models.Index(fields=['pressure', 'time_year'], name='weather_wea_pressur_cc2e87_idx'),
        ),
        migrations.AddIndex(
            model_name='weatherdata',
            index=models.Index(fields=['rain', 'time_year'], name='weather_wea_rain_932af8_idx'),
        ),
        migrations.AddIndex(
            model_name='weatherdata',
            index=models.Index(fields=['daily_rain', 'time_year'], name='weather_wea_daily_r_f95d69_idx'),
        ),
        migrations.AddIndex(
            model_name='weatherdata',
            index=models.Index(fields=['weekly_rain', 'time_year'], name='weather_wea_weekly__bbfe9f_idx'),
        ),
        migrations.AddIndex(
            model_name='weatherdata',
            index=models.Index(fields=['monthly_rain', 'time_year'], name='weather_wea_monthly_38f3d7_idx'),
        ),
        migrations.AddIndex(
            model_name='weatherdata',
            index=models.Index(fields=['solar_radiation', 'time_year'], name='weather_wea_solar_r_269259_idx'),
        ),
        migrations.AddIndex(
            model_name='weatherdata',
            index=models.Index(fields=['uv_index', 'time_year'], name='weather_wea_uv_inde_0bc6be_idx'),
        ),
    ]
