# Generated by Django 3.2.4 on 2021-07-10 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_weatherdata_time_stamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherdata',
            name='time_day',
            field=models.IntegerField(db_index=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='time_month',
            field=models.IntegerField(db_index=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='time_year',
            field=models.IntegerField(db_index=True, default=0),
            preserve_default=False,
        ),
    ]
