# Generated by Django 3.2.4 on 2021-12-29 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_auto_20210803_0524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherdata',
            name='absolute_pressure',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='daily_rain',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='dew_point',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='indoor_dew_temp',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='indoor_feels_temp',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='indoor_humidity',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='indoor_temp',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='monthly_rain',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='outdoor_dew_temp',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='outdoor_feels_temp',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='outdoor_humidity',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='outdoor_temp',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='pressure',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='rain',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='solar_radiation',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='uv_index',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='weekly_rain',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='wind_chill',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='wind_direction',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='wind_gust',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='wind_speed',
            field=models.FloatField(db_index=True),
        ),
    ]
