# Generated by Django 3.2.4 on 2022-02-06 01:13

from django.db import migrations, models
import psqlextra.manager.manager


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0006_auto_20211229_1812'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weatherdata',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelManagers(
            name='weatherdata',
            managers=[
                ('objects', psqlextra.manager.manager.PostgresManager()),
            ],
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='absolute_pressure',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='daily_rain',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='dew_point',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='indoor_dew_temp',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='indoor_feels_temp',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='indoor_humidity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='indoor_temp',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='monthly_rain',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='outdoor_dew_temp',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='outdoor_feels_temp',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='outdoor_humidity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='outdoor_temp',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='pressure',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='rain',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='solar_radiation',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='uv_index',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='weekly_rain',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='wind_chill',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='wind_direction',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='wind_gust',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='wind_speed',
            field=models.FloatField(),
        ),
    ]
