# Generated by Django 3.2.4 on 2021-09-04 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolarData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_power_usage_real', models.FloatField()),
                ('grid_power_factor', models.FloatField()),
                ('grid_power_apparent', models.FloatField()),
                ('grid_power_reactive', models.FloatField()),
                ('grid_ac_voltage', models.FloatField()),
                ('grid_ac_current', models.FloatField()),
                ('inverter_ac_frequency', models.FloatField()),
                ('inverter_ac_current', models.FloatField()),
                ('inverter_ac_voltage', models.FloatField()),
                ('inverter_ac_power', models.FloatField()),
                ('inverter_dc_current', models.FloatField()),
                ('inverter_dc_voltage', models.FloatField()),
                ('time_stamp', models.IntegerField(db_index=True)),
                ('time_year', models.IntegerField(db_index=True)),
                ('time_month', models.IntegerField(db_index=True)),
                ('time_day', models.IntegerField(db_index=True)),
            ],
        ),
    ]
