# Generated by Django 3.2.4 on 2022-02-06 06:35

from django.db import migrations, models
import psqlextra.backend.migrations.operations.add_default_partition
import psqlextra.backend.migrations.operations.create_partitioned_model
import psqlextra.manager.manager
import psqlextra.models.partitioned
import psqlextra.types


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        psqlextra.backend.migrations.operations.create_partitioned_model.PostgresCreatePartitionedModel(
            name='SolarData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_power_usage_real', models.FloatField()),
                ('grid_power_factor', models.FloatField()),
                ('grid_power_apparent', models.FloatField()),
                ('grid_power_reactive', models.FloatField()),
                ('grid_ac_voltage', models.FloatField()),
                ('grid_ac_current', models.FloatField()),
                ('inverter_ac_frequency', models.FloatField()),
                ('inverter_ac_current', models.FloatField()),
                ('inverter_ac_voltage', models.FloatField()),
                ('inverter_ac_power', models.FloatField()),
                ('inverter_dc_current', models.FloatField()),
                ('inverter_dc_voltage', models.FloatField()),
                ('power_consumption', models.FloatField()),
                ('time_stamp', models.IntegerField(db_index=True)),
                ('time_year', models.IntegerField(db_index=True)),
                ('time_month', models.IntegerField(db_index=True)),
                ('time_day', models.IntegerField(db_index=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            partitioning_options={
                'method': psqlextra.types.PostgresPartitioningMethod['RANGE'],
                'key': ['time_stamp'],
            },
            bases=(psqlextra.models.partitioned.PostgresPartitionedModel,),
            managers=[
                ('objects', psqlextra.manager.manager.PostgresManager()),
            ],
        ),
        psqlextra.backend.migrations.operations.add_default_partition.PostgresAddDefaultPartition(
            model_name='SolarData',
            name='default',
        ),
    ]
