# Generated by Django 3.2.4 on 2022-02-06 06:35

from django.db import migrations, models
from psqlextra.backend.migrations.operations import PostgresAddRangePartition


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solar', '0001_initial'),
    ]

    operations = [
        PostgresAddRangePartition(
            model_name="SolarData",
            name="2021_09",
            from_values="1630923435",
            to_values="1633010382",
        ),
        PostgresAddRangePartition(
            model_name="SolarData",
            name="2021_10",
            from_values="1633010401",
            to_values="1635685181",
        ),
        PostgresAddRangePartition(
            model_name="SolarData",
            name="2021_11",
            from_values="1635685202",
            to_values="1638277181",
        ),
        PostgresAddRangePartition(
            model_name="SolarData",
            name="2021_12",
            from_values="1638277201",
            to_values="1640955581",
        ),
        PostgresAddRangePartition(
            model_name="SolarData",
            name="2022_01",
            from_values="1640955601",
            to_values="1643633982",
        ),
        PostgresAddRangePartition(
            model_name="SolarData",
            name="2022_02",
            from_values="1643634001",
            to_values="1645966800",
        ),
    ]
