# Generated by Django 3.2.4 on 2021-09-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solardata',
            name='power_consumption',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
