# Generated by Django 3.2.4 on 2022-02-06 06:35

from django.db import migrations, models
from psqlextra.backend.migrations.operations import PostgresAddRangePartition


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solar', '0001_initial'),
    ]

    operations = [
        PostgresAddRangePartition(
            model_name="SolarData",
            name="2021_09",
            from_values="1630923435",
            to_values="1633010382",
        ),
        PostgresAddRangePartition(
            model_name="SolarData",
            name="2021_10",
            from_values="1633010401",
            to_values="1635685181",
        ),
        PostgresAddRangePartition(
            model_name="SolarData",
            name="2021_11",
            from_values="1635685202",
            to_values="1638277181",
        ),
        PostgresAddRangePartition(
            model_name="SolarData",
            name="2021_12",
            from_values="1638277201",
            to_values="1640955581",
        ),
        PostgresAddRangePartition(
            model_name="SolarData",
            name="2022_01",
            from_values="1640955601",
            to_values="1643633982",
        ),
        PostgresAddRangePartition(
            model_name="SolarData",
            name="2022_02",
            from_values="1643634001",
            to_values="1645966800",
        ),
        PostgresAddRangePartition(
            model_name="SolarData",
            name="2022_03",
            from_values="1646053200",
            to_values="1648731599",
        ),
        PostgresAddRangePartition(
            model_name="SolarData",
            name="2022_04",
            from_values="1648774667",
            to_values="1651327182",
        ),
        PostgresAddRangePartition(
            model_name="SolarData",
            name="2022_05",
            from_values="1651327202",
            to_values="1654005582",
        ),
        PostgresAddRangePartition(
            model_name="SolarData",
            name="2022_06",
            from_values="1654005601",
            to_values="1656597581",
        ),
        PostgresAddRangePartition(
            model_name="SolarData",
            name="2022_07",
            from_values="1656597602",
            to_values="1659275999",
        ),
        PostgresAddRangePartition(
            model_name="SolarData",
            name="2022_08",
            from_values="1659276000",
            to_values="1661954399",
        ),
    ]
