# Generated by Django 3.2.4 on 2021-12-29 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0002_solardata_power_consumption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solardata',
            name='grid_ac_current',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='solardata',
            name='grid_ac_voltage',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='solardata',
            name='grid_power_apparent',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='solardata',
            name='grid_power_factor',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='solardata',
            name='grid_power_reactive',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='solardata',
            name='grid_power_usage_real',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='solardata',
            name='inverter_ac_current',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='solardata',
            name='inverter_ac_frequency',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='solardata',
            name='inverter_ac_power',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='solardata',
            name='inverter_ac_voltage',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='solardata',
            name='inverter_dc_current',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='solardata',
            name='inverter_dc_voltage',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='solardata',
            name='power_consumption',
            field=models.FloatField(db_index=True),
        ),
    ]
