# Generated by Django 3.2.4 on 2022-02-06 01:13

from django.db import migrations, models
import psqlextra.manager.manager


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0003_auto_20211229_1812'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solardata',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelManagers(
            name='solardata',
            managers=[
                ('objects', psqlextra.manager.manager.PostgresManager()),
            ],
        ),
        migrations.AlterField(
            model_name='solardata',
            name='grid_ac_current',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='solardata',
            name='grid_ac_voltage',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='solardata',
            name='grid_power_apparent',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='solardata',
            name='grid_power_factor',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='solardata',
            name='grid_power_reactive',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='solardata',
            name='grid_power_usage_real',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='solardata',
            name='inverter_ac_current',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='solardata',
            name='inverter_ac_frequency',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='solardata',
            name='inverter_ac_power',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='solardata',
            name='inverter_ac_voltage',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='solardata',
            name='inverter_dc_current',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='solardata',
            name='inverter_dc_voltage',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='solardata',
            name='power_consumption',
            field=models.FloatField(),
        ),
    ]
