# Generated by Django 3.2.4 on 2022-09-16 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0003_auto_20220916_1737'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='solardata',
            name='solar_solar_grid_po_882897_idx',
        ),
        migrations.RemoveIndex(
            model_name='solardata',
            name='solar_solar_grid_po_bc17b7_idx',
        ),
        migrations.RemoveIndex(
            model_name='solardata',
            name='solar_solar_grid_po_2deb66_idx',
        ),
        migrations.RemoveIndex(
            model_name='solardata',
            name='solar_solar_grid_po_37e35c_idx',
        ),
        migrations.RemoveIndex(
            model_name='solardata',
            name='solar_solar_grid_ac_9df396_idx',
        ),
        migrations.RemoveIndex(
            model_name='solardata',
            name='solar_solar_grid_ac_3cc1a5_idx',
        ),
        migrations.RemoveIndex(
            model_name='solardata',
            name='solar_solar_inverte_0ef5ad_idx',
        ),
        migrations.RemoveIndex(
            model_name='solardata',
            name='solar_solar_inverte_3defda_idx',
        ),
        migrations.RemoveIndex(
            model_name='solardata',
            name='solar_solar_inverte_f8b004_idx',
        ),
        migrations.RemoveIndex(
            model_name='solardata',
            name='solar_solar_inverte_d535c0_idx',
        ),
        migrations.RemoveIndex(
            model_name='solardata',
            name='solar_solar_inverte_4eb991_idx',
        ),
        migrations.RemoveIndex(
            model_name='solardata',
            name='solar_solar_power_c_464782_idx',
        ),
        migrations.AddIndex(
            model_name='solardata',
            index=models.Index(fields=['time_stamp', 'grid_power_usage_real'], name='solar_solar_time_st_2d1034_idx'),
        ),
        migrations.AddIndex(
            model_name='solardata',
            index=models.Index(fields=['time_stamp', 'grid_power_factor'], name='solar_solar_time_st_5b4087_idx'),
        ),
        migrations.AddIndex(
            model_name='solardata',
            index=models.Index(fields=['time_stamp', 'grid_power_apparent'], name='solar_solar_time_st_02738e_idx'),
        ),
        migrations.AddIndex(
            model_name='solardata',
            index=models.Index(fields=['time_stamp', 'grid_power_reactive'], name='solar_solar_time_st_9726e2_idx'),
        ),
        migrations.AddIndex(
            model_name='solardata',
            index=models.Index(fields=['time_stamp', 'grid_ac_voltage'], name='solar_solar_time_st_a98a8f_idx'),
        ),
        migrations.AddIndex(
            model_name='solardata',
            index=models.Index(fields=['time_stamp', 'grid_ac_current'], name='solar_solar_time_st_67af82_idx'),
        ),
        migrations.AddIndex(
            model_name='solardata',
            index=models.Index(fields=['time_stamp', 'inverter_ac_frequency'], name='solar_solar_time_st_a9da6e_idx'),
        ),
        migrations.AddIndex(
            model_name='solardata',
            index=models.Index(fields=['time_stamp', 'inverter_ac_current'], name='solar_solar_time_st_736c35_idx'),
        ),
        migrations.AddIndex(
            model_name='solardata',
            index=models.Index(fields=['time_stamp', 'inverter_ac_voltage'], name='solar_solar_time_st_aa8eb5_idx'),
        ),
        migrations.AddIndex(
            model_name='solardata',
            index=models.Index(fields=['time_stamp', 'inverter_dc_current'], name='solar_solar_time_st_ce7bad_idx'),
        ),
        migrations.AddIndex(
            model_name='solardata',
            index=models.Index(fields=['time_stamp', 'inverter_dc_voltage'], name='solar_solar_time_st_535139_idx'),
        ),
        migrations.AddIndex(
            model_name='solardata',
            index=models.Index(fields=['time_stamp', 'power_consumption'], name='solar_solar_time_st_9ee5cf_idx'),
        ),
    ]
