# Generated by Django 3.2.4 on 2022-09-16 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0004_auto_20220916_1740'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='solardata',
            index=models.Index(fields=['time_stamp', 'inverter_ac_power'], name='solar_solar_time_st_7db798_idx'),
        ),
    ]
